#ifndef _SENSOR_NTC_H_
#define _SENSOR_NTC_H_
#include "include/stdint.h"
/********************************************************************************/
/* Temperature module: two NTC sensors (plain ADC inputs). Pin map, relay and   */
/* external-NTC switch all live in config.h (sections 4/7/8) - single source    */
/* of truth. P4.3 is the HEATING RELAY, not a sensor power switch.              */
/*                                                                              */
/* Reading: select channel, settle ~2 ms, take TEMP_AVG conversions (one        */
/* settle read is discarded; the 2 smallest + 2 largest are trimmed, the rest   */
/* averaged). The result is a 12-bit code                                       */
/* (0..4095) with VDD reference. Temp_ReadC100() maps the code to 0.01 deg C,   */
/* signed 16-bit (ZCL int16s: 20.3 C = 2030) via the NTC lookup table           */
/* (generated by CA51F253L3/tools/gen_ntc.py, ascending code, linear interp).   */
/* Parameters (B/R0/Rfix) confirmed on bench 20.1 C: 10k + 3435 + divider 10k.  */
/********************************************************************************/
#include "include/stdint.h"

#define TEMP_INTERNAL   0            /* AD_CH[0] = P4.0 (see config.h) */
#define TEMP_EXTERNAL   1            /* AD_CH[1] = P4.1 (see config.h) */

#define TEMP_AVG        12            /* conversions per read: 1 settle read is  */
                                      /* discarded, then TEMP_TRIM smallest and  */
                                      /* TEMP_TRIM largest are trimmed (spike/   */
                                      /* EMI immunity), the rest averaged        */
#define TEMP_TRIM       2             /* trim this many min AND max (code tracks */
                                      /* exactly two; keep in sync)              */
#define TEMP_TIMEOUT    0x0BB8        /* ADC poll timeout (like factory)         */

#define TEMP_ERR       0x7FFF        /* sentinel: code outside the table */

void     Temp_Init(void);               /* P43F/P44F=2 GPIO out, both off, ADC config */
uint8_t Temp_ReadC100Checked(uint8_t sensor, int16_t xdata *value_c100);
int16_t  Temp_ReadC100(uint8_t sensor); /* 0.01 deg C (ZCL int16s), or TEMP_ERR       */

#endif
