#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate NTC temperature lookup table for the thermostat temp module.

Model:        R(T) = R0 * exp(B * (1/T - 1/T0))            (B-constant NTC)
Divider:      VDD -> Rfix -> node(P4.x) -> NTC -> GND      (NTC is the low side)
ADC:          12-bit, VDD reference  ->  code = 4095*Rntc/(Rntc+Rfix)

Edit the parameters, then run:
    python gen_ntc.py            # prints the C arrays for sensor_ntc.c
    python gen_ntc.py --file     # writes them into CA51F2_test_LED/source/sensor_ntc.c

After bench calibration (raw at two known temperatures) adjust R0/B/geometry
and regenerate. Output arrays are sorted ascending by code.
"""
import math
import re
import sys

# ---- NTC parameters (adjust after bench calibration) ----------------
B     = 3435.0     # NTC material constant, K (10k B=3435: common stats type)
R0    = 10000.0    # NTC nominal resistance at T0, ohm (confirmed 10k)
T0C   = 25.0       # reference temperature for R0, deg C
RFIX  = 10000.0    # series resistor (divider high side), ohm (assumed matched)
FS    = 4095.0     # full scale 12-bit ADC code
TLOW  = -10        # table range low, deg C
THIGH = 60         # table range high, deg C
STEP  = 2          # table step, deg C

T0K = T0C + 273.15

def r_ntc(t_c):
    return R0 * math.exp(B * (1.0 / (t_c + 273.15) - 1.0 / T0K))

def code_for(t_c):
    r = r_ntc(t_c)
    return int(round(FS * r / (r + RFIX)))

def build():
    pairs = [(code_for(t), int(t * 100)) for t in range(TLOW, THIGH + 1, STEP)]
    pairs.sort(key=lambda p: p[0])              # ascending code
    return [c for c, _ in pairs], [t for _, t in pairs]

def fmt(arr, width, per):
    line = ""
    for i, v in enumerate(arr):
        line += ("%*d, " % (width, v)) if i % per != per - 1 else ("%*d,\n" % (width, v))
    return line

def arrays_text(codes, temps):
    out = []
    out.append("/* auto-generated by tools/gen_ntc.py: B=%.0f R0=%.0f Rfix=%.0f, %d..%d C, step %d */"
               % (B, R0, RFIX, TLOW, THIGH, STEP))
    # Keil C51: 'code' storage class (read-only ROM), NOT 'static const' (DATA!)
    out.append("const unsigned int code ntc_code[] = {")
    out.append(fmt(codes, 5, 9))
    out.append("};")
    out.append("const int16_t code ntc_c100[] = {")
    out.append(fmt(temps, 6, 9))
    out.append("};")
    return "\n".join(out) + "\n"

def patch_temp_c(text, block):
    """Replace the generated block between markers in sensor_ntc.c."""
    m1 = text.index("/* >>> GENERATED-BEGIN")
    m2 = text.index("/* >>> GENERATED-END")
    tail = text.index("\n", m2) + 1
    head = text[:m1]
    new = ("/* >>> GENERATED-BEGIN (auto-generated: tools/gen_ntc.py) >>> */\n"
           + block +
           "/* >>> GENERATED-END */\n")
    return head + new + text[tail:]
    # NOTE: markers must already be present in source/sensor_ntc.c.

def main():
    codes, temps = build()
    block = arrays_text(codes, temps)
    if "--file" in sys.argv:
        path = r"CA51F2_test_LED/source/sensor_ntc.c"
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        text = patch_temp_c(text, block)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        print("patched %s" % path)
    else:
        print("n=%d (range %d..%d C by %d, ascending code)" % (len(codes), TLOW, THIGH, STEP))
        print(block)

if __name__ == "__main__":
    main()