#!/usr/bin/env python
"""Generate clang (mcs51-llvm) SFR headers and linker symbols.

The SDCC headers (include/ca51f2sfr.h, include/ca51f2xsfr.h) stay the single
source of truth and are never modified. This tool derives from them:

  <outdir>/include/ca51f2sfr.h   clang SFR/SBIT extern declarations
                                 (SDCC `__sfr __at(addr) NAME;` has no clang
                                 equivalent - the address is supplied as an
                                 absolute symbol by the linker script);
  <outdir>/include/ca51f2xsfr.h  clang XSFR extern declarations
                                 (`XRAM_U8(NAME, addr)` -> extern __xdata);
  <outdir>/sfr_symbols.ld        `NAME = 0xADDR;` absolute symbols consumed
                                 by ld.lld via a second -T script.

The clang build puts <outdir> on the include path BEFORE include/, so the
generated headers shadow the SDCC ones (sources include "include/xxx.h").
"""

import argparse
import re
import sys
from pathlib import Path

SFR_RE = re.compile(
    r"^(\s*)__sfr\s+__at\(\s*(0[xX][0-9a-fA-F]+)\s*\)\s*(\w+)\s*;\s*$")
SBIT_RE = re.compile(
    r"^(\s*)__sbit\s+__at\(\s*(0[xX][0-9a-fA-F]+)\s*\)\s*(\w+)\s*;\s*$")
XU8_RE = re.compile(
    r"^\s*XRAM_U8\s*\(\s*(\w+)\s*,\s*(0[xX][0-9a-fA-F]+)\s*\)\s*;\s*$")
XU16_RE = re.compile(
    r"^\s*XRAM_U16\s*\(\s*(\w+)\s*,\s*(0[xX][0-9a-fA-F]+)\s*\)\s*;\s*$")

XSFR_GUARD = "__CA51F2_XDATA_H__"


def gen_sfr_header(text):
    """Rewrite __sfr/__sbit __at() declarations into clang externs."""
    out = []
    symbols = []
    for line in text.splitlines():
        m = SFR_RE.match(line)
        if m:
            out.append("%sextern volatile __sfr unsigned char %s;"
                       % (m.group(1), m.group(3)))
            symbols.append((m.group(3), int(m.group(2), 16)))
            continue
        m = SBIT_RE.match(line)
        if m:
            out.append("%sextern volatile __sbit unsigned char %s;"
                       % (m.group(1), m.group(3)))
            symbols.append((m.group(3), int(m.group(2), 16)))
            continue
        out.append(line)
    if not symbols:
        raise SystemExit("gen_clang_sfr: no __sfr/__sbit declarations found")
    return "\n".join(out) + "\n", symbols


def gen_xsfr_header(text):
    """Regenerate the XSFR header with the SDCC owner-TU pattern.

    lld's MCS-51 space check only trusts input-section names, so the address
    cannot come from a bare absolute symbol: the owner translation unit
    (_MAIN_C_, src/main.c) must emit a real xdata object, placed into a
    per-register section by the generated linker script; every other TU sees
    an extern.
    """
    instances = []
    for line in text.splitlines():
        m = XU8_RE.match(line)
        if m:
            instances.append(("XRAM_U8", m.group(1), int(m.group(2), 16), 8))
            continue
        m = XU16_RE.match(line)
        if m:
            instances.append(("XRAM_U16", m.group(1), int(m.group(2), 16), 16))
            continue
    if not instances:
        raise SystemExit("gen_clang_sfr: no XRAM_U8/XRAM_U16 declarations")
    lines = [
        "#ifndef %s" % XSFR_GUARD,
        "#define %s" % XSFR_GUARD,
        "/* Generated by tools/gen_clang_sfr.py - do not edit. */",
        "/* Addresses come from the per-register sections placed by          */",
        "/* sfr_symbols.ld; the owner TU (_MAIN_C_) emits the objects.        */",
        "#if defined(_MAIN_C_)",
    ]
    symbols = []
    for _macro, name, addr, bits in instances:
        ctype = "unsigned char" if bits == 8 else "unsigned int"
        lines.append("volatile %s __xdata __attribute__((section("
                     "\".mcs51.xdata.sfr.%s\"))) %s;" % (ctype, name, name))
        symbols.append((name, addr))
    lines.append("#else")
    for _macro, name, _addr, bits in instances:
        ctype = "unsigned char" if bits == 8 else "unsigned int"
        lines.append("extern volatile %s __xdata %s;" % (ctype, name))
    lines.append("#endif")
    lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n", symbols


def gen_symbols_ld(sfr_symbols, xsfr_symbols):
    """Absolute symbols for SFR/SBIT; named sections for the XSFR window.

    lld's MCS-51 space check only recognises XDATA targets by section name
    (.mcs51.xdata.*), so every MOVX-accessed register gets its own empty
    NOLOAD output section at the register address. SFR/bit registers are
    direct/bit-addressed (relocation types the check does not classify) and
    stay plain absolute symbols.
    """
    lines = [
        "/* Generated by tools/gen_clang_sfr.py - do not edit. */",
        "/* SFR/SBIT/XSFR addresses extracted from the SDCC headers.       */",
        "",
        "/* SFR (direct and bit address space) */",
    ]
    seen = {}
    for name, addr in sfr_symbols:
        if name in seen and seen[name] != addr:
            raise SystemExit(
                "gen_clang_sfr: duplicate symbol %s (0x%x vs 0x%x)"
                % (name, seen[name], addr))
        seen[name] = addr
        lines.append("%s = 0x%x;" % (name, addr))
    lines.append("")
    lines.append("/* XSFR (XDATA-mapped registers: per-register sections so the")
    lines.append("   lld space check sees the MOVX targets as XDATA) */")
    for name, addr in xsfr_symbols:
        if name in seen and seen[name] != addr:
            raise SystemExit(
                "gen_clang_sfr: duplicate symbol %s (0x%x vs 0x%x)"
                % (name, seen[name], addr))
        seen[name] = addr
        lines.append(".mcs51.xdata.sfr.%s 0x%x (NOLOAD) :"
                     " { *(.mcs51.xdata.sfr.%s) } > XSFR"
                     % (name, addr, name))
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--sfr", required=True, help="path to ca51f2sfr.h")
    ap.add_argument("--xsfr", required=True, help="path to ca51f2xsfr.h")
    ap.add_argument("--outdir", required=True, help="output directory")
    args = ap.parse_args()

    sfr_text = Path(args.sfr).read_text(encoding="utf-8", errors="replace")
    xsfr_text = Path(args.xsfr).read_text(encoding="utf-8", errors="replace")

    sfr_hdr, sfr_syms = gen_sfr_header(sfr_text)
    xsfr_hdr, xsfr_syms = gen_xsfr_header(xsfr_text)
    ld_text = gen_symbols_ld(sfr_syms, xsfr_syms)

    outdir = Path(args.outdir)
    (outdir / "include").mkdir(parents=True, exist_ok=True)
    (outdir / "include/ca51f2sfr.h").write_text(sfr_hdr, encoding="utf-8")
    (outdir / "include/ca51f2xsfr.h").write_text(xsfr_hdr, encoding="utf-8")
    (outdir / "sfr_symbols.ld").write_text(ld_text, encoding="utf-8")

    print("gen_clang_sfr: %d SFR/SBIT + %d XSFR symbols -> %s"
          % (len(sfr_syms), len(xsfr_syms), outdir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
