"""Convert the flasher Intel HEX (linked at 0x8000) into a C byte array.

Usage: python tools/make_flasher_blob.py <flasher.ihx> <out.c>
Bytes are emitted in ascending address order starting at 0x8000; the array is
copied verbatim to XRAM 0x0000 by the app.
"""
import sys

BASE = 0x8000


def read_ihx(path):
    mem = {}
    ext = 0
    for line in open(path):
        line = line.strip()
        if not line.startswith(":"):
            continue
        b = bytes.fromhex(line[1:])
        count, addr, rectype = b[0], (b[1] << 8) | b[2], b[3]
        data = b[4:4 + count]
        if rectype == 0x00:
            for i, v in enumerate(data):
                mem[ext + addr + i] = v
        elif rectype == 0x02:
            ext = ((data[0] << 8) | data[1]) << 4
        elif rectype == 0x04:
            ext = ((data[0] << 8) | data[1]) << 16
    return mem


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: make_flasher_blob.py <flasher.ihx> <out.c>")
    mem = read_ihx(sys.argv[1])
    used = sorted(a for a in mem if a >= BASE)
    if not used or used[0] != BASE:
        sys.exit("flasher image does not start at 0x%X" % BASE)
    end = used[-1]
    blob = bytes(mem.get(a, 0xFF) for a in range(BASE, end + 1))
    if len(blob) >= 0x0600:
        sys.exit("flasher too big: %d bytes (must be < 0x600)" % len(blob))
    with open(sys.argv[2], "w") as f:
        f.write("/* generated by tools/make_flasher_blob.py - do not edit */\n")
        f.write('#include "include/stdint.h"\n')
        f.write("const uint16_t code flasher_blob_len = %d;\n" % len(blob))
        f.write("const uint8_t code flasher_blob[] = {\n")
        for i in range(0, len(blob), 12):
            f.write("\t" + ", ".join("0x%02X" % v for v in blob[i:i + 12]) + ",\n")
        f.write("};\n")
    print("flasher blob: %d bytes" % len(blob))


if __name__ == "__main__":
    main()
