/*******************************************************************************/
#include "include/stdint.h"
#include "include/config.h"
#include "include/ca51f2sfr.h"
#include "include/ca51f2xsfr.h"
#include "include/gpiodef_f2.h"
#include "include/delay.h"
#include "include/sensor_ntc.h"
/*******************************************************************************/
/* ADC register helpers (Keil C51: no stdint types needed here, plain macros)  */
#define AST(N)         ((N) << 7)        /* ADC start                        */
#define ADIE(N)        ((N) << 6)        /* interrupt enable (unused)        */
#define ADIF           (1 << 5)          /* conversion done flag             */
#define HTME(N)        ((N) << 2)        /* sample time 2^N ADC clocks       */
#define VSEL(N)        (N)               /* ref: 0 inner 1.5V, 1 VDD, 2 ext  */
#define ACKD(N)        ((N) << 5)        /* ADC clock divider, / (N+1)       */
#define ADCHS(N)       (N)               /* channel: 1 = CH0, 2 = CH1 ...    */
#define VTRIM(N)       (N)
#define ADC_CH0        1
#define ADC_CH1        2
#define ADC_REF_VDD    1
/*************************************************************************************/
/* >>> GENERATED-BEGIN (auto-generated: tools/gen_ntc.py) >>>                        */
/* auto-generated by tools/gen_ntc.py: B=3435 R0=10000 Rfix=10000, -10..60 C, step 2 */
const uint16_t code ntc_code[] = {
  940,   986,  1034,  1084,  1137,  1191,  1248,  1307,  1368,
 1431,  1496,  1564,  1634,  1705,  1778,  1854,  1930,  2008,
 2087,  2167,  2248,  2329,  2411,  2492,  2573,  2654,  2733,
 2812,  2888,  2964,  3037,  3108,  3177,  3243,  3307,  3368,

};
/* >>> GENERATED-END */

/* Temperature column of the generated table is a perfect ramp 6000 - 200*i
   (0.01 deg C per 2 deg C entry), so it is computed instead of stored (-72 B
   ROM). tools/gen_ntc.py still emits it as ntc_c100[] - re-running --file
   targets the prototype tree, not this file.                                  */
#define NTC_C100_0     6000
#define NTC_C100_STEP  200
#define NTC_C100_AT(i) ((int16_t)(NTC_C100_0 - NTC_C100_STEP * (int16_t)(i)))

#define NTC_N   (sizeof(ntc_code) / sizeof(ntc_code[0]))
/********************************************************************************/
/* Sensor presence: raw code must sit inside a window bracketing the NTC table. */
/* Open sensor (divider node pulled to VDD, code ~4095) or shorted sensor       */
/* (code ~0) fall outside and are reported as TEMP_ERR ("no sensor").           */
#define TEMP_CODE_MIN    900
#define TEMP_CODE_MAX    3450
/********************************************************************************/
static void temp_select(uint8_t sensor) {
	ADCFGL = (ADCFGL & 0xF0) | ADCHS((sensor == TEMP_INTERNAL) ? ADC_CH0 : ADC_CH1);
}

static void temp_power(uint8_t sensor, uint8_t on) {
	/* P4.3 is the heating relay (config.h section 7), NOT a sensor power
	   switch: do NOT drive it here (that would pulse the relay every
	   measurement). The internal NTC is a plain ADC input (P4.0), always on. */
	if(sensor == TEMP_EXTERNAL) {
		NTC_EXT_SW_PIN = on ? NTC_EXT_SW_ON : NTC_EXT_SW_OFF;   /* unverified */
	}
}

static uint16_t temp_adc_value;

static uint8_t temp_conv_once(void) {
	uint16_t tout = TEMP_TIMEOUT;

	ADCON |= AST(1);
	while(!(ADCON & ADIF)) {
		if(--tout == 0) {
			ADCON &= (uint8_t)~AST(1);
			ADCON |= ADIF;
			return 0;
		}
	}
	ADCON |= ADIF;
	temp_adc_value = ((uint16_t)ADCDH << 8) | (uint16_t)ADCDL;
	return 1;
}
/********************************************************************************/
void Temp_Init(void) {
	P40F = P40_ADC0_SETTING;             /* CH0 analog input  (internal NTC)   */
	P41F = P41_ADC1_SETTING;             /* CH1 analog input  (external NTC)   */
	P44F = OUTPUT;                       /* P4.4 = external NTC switch (cfg 8) */
	temp_power(TEMP_INTERNAL, 0);
	temp_power(TEMP_EXTERNAL, 0);
	/* NOTE: the heating relay (P4.3) is initialised by Relay_Init() (relay.c). */

	ADCON   = AST(0) | ADIE(0) | HTME(7) | VSEL(ADC_REF_VDD);
	ADCFGH  = VTRIM(8);
	ADCFGL  = (uint8_t)(ACKD(7) | ADCHS(ADC_CH0));
}
/*******************************************************************************/
static uint8_t temp_read_raw_checked(uint8_t sensor, uint16_t xdata *raw) {
	uint16_t acc, v;
	uint16_t min1, min2, max1, max2;
	uint8_t i;
	uint8_t ok;

	acc  = 0;
	min1 = min2 = 0xFFFF;
	max1 = max2 = 0;
	*raw = 0;
	temp_select(sensor);
	temp_power(sensor, 1);
	Delay_ms(2);
	ok = 1;
	for(i = 0; i < TEMP_AVG + 1; i++) {
		if(!temp_conv_once()) {
			ok = 0;
			break;
		}
		if(i == 0) continue;
		v = temp_adc_value >> 4;
		acc += v;
		if(v < min1)      { min2 = min1; min1 = v; }
		else if(v < min2) { min2 = v; }
		if(v > max1)      { max2 = max1; max1 = v; }
		else if(v > max2) { max2 = v; }
	}
	temp_power(sensor, 0);
	if(!ok) return 0;
	acc -= (uint16_t)(min1 + min2 + max1 + max2);
	*raw = acc / (TEMP_AVG - 2 * TEMP_TRIM);
	return 1;
}
/*******************************************************************************/
uint8_t Temp_ReadC100Checked(uint8_t sensor, int16_t xdata *value_c100) {
	uint16_t adc;
	uint16_t i;

	*value_c100 = TEMP_ERR;
	if(!temp_read_raw_checked(sensor, &adc)) return 0;
	if((adc < TEMP_CODE_MIN) || (adc > TEMP_CODE_MAX)) return 0;

	if(adc <= ntc_code[0]) {
		*value_c100 = NTC_C100_AT(0);
		return 1;
	}

	for(i = 1; i < NTC_N; i++) {
		if(adc <= ntc_code[i]) {
			uint16_t c0 = ntc_code[i - 1];
			uint16_t c1 = ntc_code[i];
			int16_t t0 = NTC_C100_AT(i - 1);
			uint16_t d  = (uint16_t)(adc - c0);
			/* consecutive entries are always NTC_C100_STEP apart, so the
			   old (t0 - t1) factor collapses to that constant           */
			uint16_t numerator = (uint16_t)(NTC_C100_STEP * (int16_t)d);
			uint8_t denominator = (uint8_t)(c1 - c0);
			uint16_t dt = 0;

			while(numerator >= denominator) {
				numerator -= denominator;
				dt++;
			}
			*value_c100 = (int16_t)(t0 - (int16_t)dt);
			return 1;
		}
	}

	*value_c100 = NTC_C100_AT(NTC_N - 1);
	return 1;
}
/*******************************************************************************/
#if SENSOR_LEGACY_READ
int16_t Temp_ReadC100(uint8_t sensor) {
	int16_t value;

	(void)Temp_ReadC100Checked(sensor, &value);
	return value;
}
#endif /* SENSOR_LEGACY_READ */